
export const INCREMENT = 'INCREMENT'
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESSFUL = 'FETCH_USER_SUCCESSFUL'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'